working in CI/CD

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -147,10 +147,10 @@ jobs:
           # Explicitly remove images if still present
           echo "Removing old images..."
           for image_id in $(sudo docker images -q); do
-             if [ -n "$image_id" ]; then  # Check if image_id is not empty
-                echo "Removing image ID: $image_id" 
-                sudo docker rmi -f "$image_id" || echo "Failed to remove image ID: $image_id"
-              fi
+            if [ -n "$image_id" ]; then  # Check if image_id is not empty
+              echo "Removing image ID: $image_id" 
+              sudo docker rmi -f "$image_id" || echo "Failed to remove image ID: $image_id"
+            fi
           done
           # Clone the repository
           echo "Cloning repository..."
